// Bundles the editor page (web/editor.ts + web/editor.css) with esbuild into one HTML
// document and writes it as a string to src/editor-html.ts: the component loads it into
// the WebView from memory, so the editor needs no files and no network.
//
// Run: node scripts/build-web.mjs

import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const bundle = async (entry) =>
  (
    await build({
      entryPoints: [join(root, entry)],
      bundle: true,
      minify: true,
      format: "iife",
      target: ["safari16"],
      write: false,
      legalComments: "none",
    })
  ).outputFiles[0].text;
// Two scripts: a small one that draws the text at once, then the editor.
const prerender = await bundle("web/prerender.ts");
const js = await bundle("web/editor.ts");
const css = readFileSync(join(root, "web/editor.css"), "utf8");

// A strict CSP: inline script and style only, nothing from the network. __INITIAL__ is
// replaced by the component with the text and theme, so the first paint is already right.
const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:;">
<style>${css}</style>
</head>
<body>
<div id="editor"></div>
<script>window.__initial = __INITIAL__;</script>
<script>${prerender}</script>
<script>${js}</script>
</body>
</html>`;

writeFileSync(
  join(root, "src/editor-html.ts"),
  // Typed by hand so the .d.ts holds one word, not the whole page.
  `// Generated by scripts/build-web.mjs from web/: do not edit.\nexport const EDITOR_HTML: string = ${JSON.stringify(html)};\n`
);
console.log(
  `editor page: ${(html.length / 1024).toFixed(0)} KB (prerender ${(prerender.length / 1024).toFixed(0)} KB)`
);
